README.md
docs/sphinx/code_structure.rst
docs/sphinx/components.rst
docs/sphinx/examples.rst
docs/sphinx/introduction.rst
examples/1D-periodic/makeplot.py

More documentation

---

.github/workflows/tests.yml
CMakeLists.txt
examples/1D-neon/BOUT.inp
examples/1D-periodic/BOUT.inp
examples/1D-recycling/BOUT.inp
examples/1D-sheath-conduction/BOUT.inp
examples/1D-sheath/BOUT.inp
examples/1D-te-ti/BOUT.inp
examples/blob2d-te-ti/BOUT.inp
examples/blob2d-te/BOUT.inp
examples/blob2d/BOUT.inp
hermes-3.cxx
src/vorticity.cxx
tests/integrated/1D-fluid/data/BOUT.inp
tests/integrated/diffusion/data/BOUT.inp
tests/integrated/evolve_density/data/BOUT.inp
tests/integrated/vorticity/data/BOUT.inp
tests/unit/test_extras.hxx

Mainly changes to the Options, which are now case sensitive and more strict. 
Updates to the CMake build, and adding github action test

Update to latest BOUT++ next branch

---

src/div_ops.cxx
tests/unit/test_extras.hxx

Update to BOUT++ next branch, fixes for 3D coordinates changes.
Hermes-3 will only (currenly) work with 2D coordinates, but this means dz has changed from scalar to Field2D.

Latest BOUT++ next

---

examples/1D-hydrogen/BOUT.inp
examples/1D-hydrogen/README.md
examples/1D-hydrogen/plot_convergence.py
examples/1D-hydrogen/qn/BOUT.inp
include/upstream_density_feedback.hxx
src/upstream_density_feedback.cxx

SD1D-like case, with pure deuterium. 100% recycling so the accuracy of particle conservation can be tested.

1D-hydrogen example

---

examples/blob2d/README.md
examples/blob2d/blob_size_scan.py
examples/blob2d/blob_velocity.py

Performs a scan in blob size in three passes:
- Creates input files
- Runs the simulations
- Analyses the output
Steps are skipped if they have already been done, allowing cases to be added incrementally without rerunning everything.
The script can be customised with arguments (use --help to see options).

blob2d example analysis scripts

---

CMakeLists.txt
hermes-3.cxx
include/relax_potential.hxx
src/makefile
src/relax_potential.cxx

Will solve the potential using a relaxation method.
Not yet complete or working.

Beginning a relax_potential component

---

CMakeLists.txt
examples/1D-hydrogen/BOUT.inp
examples/1D-hydrogen/qn/BOUT.inp
examples/1D-neon-source/BOUT.inp
examples/1D-neon/BOUT.inp
examples/1D-neon/add_vars_to_restarts.py
examples/1D-neon/makeplot.py
hermes-3.cxx
include/adas_neon.hxx
include/evolve_density.hxx
include/evolve_momentum.hxx
include/evolve_pressure.hxx
include/hermes_utils.hxx
include/ion_viscosity.hxx
src/adas_reaction.cxx
src/evolve_density.cxx
src/evolve_momentum.cxx
src/evolve_pressure.cxx
src/ion_viscosity.cxx
src/makefile
src/sheath_boundary.cxx

For all ion species (everything not an electron), add parallel viscosity, using the Braginskii expression.
Useful in damping initial transients in neon simulations

Ion viscosity

---

docs/sphinx/components.rst
examples/tokamak/isothermal/BOUT.inp
examples/tokamak/isothermal/makeplots.py
examples/tokamak/recycling-dthe-drifts/BOUT.inp
hermes-3.cxx
include/component.hxx
include/evolve_density.hxx
include/evolve_momentum.hxx
include/evolve_pressure.hxx
include/sheath_boundary.hxx
include/vorticity.hxx
src/diamagnetic_drift.cxx
src/electron_force_balance.cxx
src/evolve_density.cxx
src/evolve_momentum.cxx
src/evolve_pressure.cxx
src/isothermal.cxx
src/relax_potential.cxx
src/sheath_boundary.cxx
src/sound_speed.cxx
src/vorticity.cxx

Misc improvements aimed at running 2D transport simulations with electric field and drifts.
Work in progress

Parallel current, 2D with drifts

---

CMakeLists.txt
README.md
docs/sphinx/components.rst
examples/1D-hydrogen-equalT/BOUT.inp
hermes-3.cxx
include/hydrogen_charge_exchange.hxx
include/transform.hxx
src/component_scheduler.cxx
src/hydrogen_charge_exchange.cxx
src/makefile
src/transform.cxx
tests/unit/test_hydrogen_charge_exchange.cxx

Previously used Amjuel 0.1T, which is the elastic collision rate.
Now using 3.1.8 which is charge exchange.

Important: Change hydrogen CX rate

---

CMakeLists.txt
examples/solkit-comparison/makeplots.py
examples/solkit-comparison/single-temperature/BOUT.inp
examples/solkit-comparison/two-temperatures/BOUT.inp
hermes-3.cxx
include/sheath_boundary_simple.hxx
include/solkit_hydrogen_charge_exchange.hxx
include/solkit_neutral_parallel_diffusion.hxx
src/makefile
src/sheath_boundary_simple.cxx
src/solkit_hydrogen_charge_exchange.cxx
src/solkit_neutral_parallel_diffusion.cxx

Adding components and example inputs for comparison to SOL-KiT 1D SOL code.

WIP: SOL-KiT components

---

CMakeLists.txt
docs/sphinx/components.rst
hermes-3.cxx
include/evolve_momentum.hxx
include/fixed_fraction_radiation.hxx
src/evolve_momentum.cxx

Some simple models of impurity radiation from carbon, nitrogen, neon and argon.

Fixed fraction radiation models

---

include/isothermal.hxx
src/isothermal.cxx
tests/unit/test_isothermal.cxx

Allow temperature to be a function of position

Extend isothermal component

---

CMakeLists.txt
hermes-3.cxx
include/sheath_boundary_insulating.hxx
src/makefile
src/sheath_boundary.cxx
src/sheath_boundary_insulating.cxx
src/vorticity.cxx

Improvement to the sheath boundary conditions and potential calculations
- Set `phi` outer boundary cells in `vorticity` component
- Add `sheath_boundary_insulating` component, which sets j = 0

Potentials and sheaths

---

include/polarisation_drift.hxx
include/sound_speed.hxx
src/anomalous_diffusion.cxx
src/evolve_density.cxx
src/polarisation_drift.cxx
src/sheath_boundary_simple.cxx
src/sound_speed.cxx
src/vorticity.cxx

Working on improving robustness of multi-ion turbulence simulations (in linear device).

More sheath improvements

---

CMakeLists.txt
docs/sphinx/components.rst
hermes-3.cxx
include/neutral_boundary.hxx
src/neutral_boundary.cxx

Adds a heat loss through Y boundaries for a single species.

Add neutral_boundary component

---

examples/1D-periodic/plotstuff.py
examples/1D-recycling/plotstuff.py
examples/1D-sheath-conduction/plotstuff.py
examples/1D-sheath/plotstuff.py
examples/1D-te-ti/plotstuff.py
examples/2D-drift-plane-turbulence-te-ti/plotstuff.py
examples/blob2d-te-ti/plotstuff.py
examples/blob2d-te/plotstuff.py
examples/blob2d/plotstuff.py
examples/tokamak/diffusion-conduction/plotstuff.py
examples/tokamak/diffusion-flow-evolveT/plotstuff.py
examples/tokamak/diffusion-transport/plotstuff.py
examples/tokamak/diffusion/plotstuff.py
examples/tokamak/recycling-dthe-drifts/plotstuff.py
examples/tokamak/recycling-dthe/plotstuff.py
examples/tokamak/recycling-dthene/plotstuff.py
examples/tokamak/recycling/plotstuff.py

Some scripts for quickly checking the examples, by making animations using xhermes/xBOUT.
For merging into #75.

Scripts to make animations for most examples using xhermes

---

docs/sphinx/components.rst
include/recycling.hxx
src/recycling.cxx
tests/unit/test_recycling.cxx

Gives recycled particles a non-zero energy, for example the Franck-Condon energy of recycled hydrogen atoms.

Add recycle_energy to recycling component

---

docs/sphinx/examples.rst

`2D-drift-plane-turbulence-te-ti` example:  Putting all equations into SI + eV units

Manual updates, additions

---

docs/sphinx/examples.rst

* Fix factor of \bar{n} in the definition of vorticity for model written in SI.

Even more manual updates

---

CMakeLists.txt
hermes-3.cxx
include/adas_carbon.hxx
include/adas_neon.hxx

Adding carbon impurities in the same way that neon impurities are already added

Carbon impurities

---

examples/tokamak/heat-transport/BOUT.inp
examples/tokamak/heat-transport/README.md
examples/tokamak/heat-transport/analyse_fluxes.py
src/anomalous_diffusion.cxx
src/div_ops.cxx

Trying to ensure that transport equations conserve power fluxes, starting with simple diffusion.

WIP: Fixes and tests for power balance

---

src/sheath_boundary.cxx
src/sheath_boundary_simple.cxx

Further updates for applying potentials to sheath boundaries

Sheath wall potential updates

---

examples/1D-conduction/BOUT.inp
examples/1D-conduction/README.md
examples/1D-recycling/README.md
hermes-3.cxx
include/evolve_pressure.hxx
src/evolve_pressure.cxx
src/neutral_mixed.cxx

Dn should be vth^2 / sigma, where vth is the thermal speed, and sigma is the collision frequency.
Previously Dn = Pn / sigma
Should be Dn = (Tn / AA) / sigma
Boundary condition at sheath now applied to Pnlim.
If diagnose=true, output temperature field.

neutral_mixed fixes

---

NOTICE
README.md

Released under GPLv3 license LLNL-CODE-845139

Update README and add LLNL notice

---

CMakeLists.txt
tests/integrated/sod-shock/README.md
tests/integrated/sod-shock/data/BOUT.inp
tests/integrated/sod-shock/runtest

Tests handling of shocks and characteristics

Add sod shock test case

---

include/vorticity.hxx
src/vorticity.cxx

In the DOxygen comments, so should be pulled into the online manual

Add documentation of vorticity component inputs

---

CMakeLists.txt
docs/sphinx/components.rst
hermes-3.cxx
include/electron_viscosity.hxx
src/anomalous_diffusion.cxx
src/electron_viscosity.cxx

Braginskii parallel electron viscosity

Add electron_viscosity component

---

examples/1D-recycling/BOUT.inp

@mikekryjak @georgeholt1 @matthewbkhan

Extend documentation for 1D-recycling

---

.readthedocs.yml
docs/sphinx/components.rst

Didn't seem to be needed previously.

Adding .readthedocs.yml config file

---

CMakeLists.txt
hermes-3.cxx
include/classical_diffusion.hxx
src/classical_diffusion.cxx

Adds basic diffusion of particles, and energy due to classical diffusion. Doesn't yet include viscosity or things like the thermal pinch term.

classical_diffusion component

---

docs/sphinx/components.rst
src/binormal_stpm.cxx

This adds a documentation section for the binormal_stpm component, while also reworking the model to be a bit more consistent with the published one.

Add documentation and slightly rework binormal_stpm

---

examples/tcv-x21/convert_to_tcvx21.py
examples/tcv-x21/data/BOUT.inp
examples/tcv-x21/gather_data.py
examples/tcv-x21/make_tcvx21_plots.py
hermes-3.cxx
include/hermes_build_config.hxx.in
include/ion_viscosity.hxx
include/polarisation_drift.hxx
include/vorticity.hxx
src/ion_viscosity.cxx
src/polarisation_drift.cxx
src/vorticity.cxx

Improvements to the `ion_viscosity` and `vorticity` components
Taking the toroidal (Z) average of the poloidal viscosity component. In published work the flux-surface average is usually used for this neoclassical piece, but I don't know how this would work for open field-lines. The non-constant in Z components seem to cause numerical trouble, but the axisymmetric component is well behaved (so far!)
The energy exchange between ion pressure and vorticity is a bit tricky. If ion pressure (diamagnetic flow) is included in the vorticity then there should be a term in the pressure equation like `(pi / n0) * Div(Jpar + Jdia)`. This term arises from the divergence of polarisation drift: The Boussinesq approximation means that vpol is like J / n0. This:
- Can't be calculated in `vorticity` because …

Poloidal viscosity and polarisation drift energy exchange

---

README.md

Add reference to xHermes at the top of readme

Add reference to xHermes at the top of readme

---

docs/requirements.txt

ReadTheDocs complaining about recommonmark module not being installed.

Try to fix readthedocs failures

---

docs/sphinx/tests.rst

Some documentation of the drift-wave test case

Adding documentation

---

src/electron_force_balance.cxx
src/evolve_energy.cxx

Investigating an anomaly in the temperature near the sheath: Sometimes the temperature ticks up in the last few grid cells.

WIP: Boundaries and misc fixes

---

docs/sphinx/detachment_controller.rst
docs/sphinx/index.rst

Documentation to go with PR #209. Thanks @tbody-cfs !
Converted from Markdown to RST using Pandoc.

Documenting detachment_controller component

---

include/amjuel_reaction.hxx

As per title. Ready for review

Fix radiation multiplier not affecting 13.6eV e heating in recombination

---

include/binormal_stpm.hxx
src/binormal_stpm.cxx
src/evolve_energy.cxx
src/evolve_pressure.cxx

Fix STPM component

---

include/fixed_fraction_radiation.hxx

Finally fixing the sign convention...

Fix sign of impurity radiation diagnostics

---

include/sound_speed.hxx
src/sound_speed.cxx

This allows you to scale the force of the lax flux, and so is very useful for debugging. 
Works fine and ready for merge

Add factor to scale fastest_wave in sound_speed.cxx

---

tests/unit/test_extras.hxx

Includes improvements to beuler solver

Updating BOUT++ version

---

docs/sphinx/installation_using_cmake.rst

Add perlmutter compilation docs

---

docs/sphinx/examples.rst
examples/tokamak-1D/1D-threshold/BOUT.inp

Fixes minor typos in the recent 1D-threshold PR

Fix 1 d threshold

---

docker/Dockerfile
docker/image_ingredients/docker_image_commands.sh

Small edit to store library builds in the work folder.

Enable reusable build with docker image

---

.github/workflows/build_builder_image.yml
.github/workflows/build_docker_image.yml
.github/workflows/build_jupyter_image.yml
.github/workflows/tests.yml
docker/hermes-3-builder.dockerfile
docker/hermes-3.dockerfile
docker/image_ingredients/docker_spack.yaml

Need to remove existing images from https://github.com/orgs/boutproject/packages before merging this PR
These fixes tidy up the docker build tags.
I experimented with multi-arch builds (for arm as well as x86), but these don't work out of the box. If requested, I can repair these.
To try out the docker image, copy https://raw.githubusercontent.com/boutproject/hermes-3/refs/heads/master/docker/development-setup.sh to your local machine and execute it. This will make a folder `hermes-3-docker`. `cd` into that folder, then run `docker compose run hermes work/hermes-3/examples/tokamak-1D/1D-threshold`. To analyze this run, run `docker compose up jupyter` and open the Jupyter server.

Docker minor fixes

---

include/ion_viscosity.hxx
src/ion_viscosity.cxx

Added neoclassical correction to ion viscosity based on ion bounce time to ion collision time ratio, as per GRILLIX 2024 and Rozhansky 2009. New diagnostics: bounce_factor, the reduction factor for viscosity, and nu-star, the ratio t_bounce / t_collision.

Ion viscosity neoclassical
