- docs/sphinx/components.rst
- examples/1D-sheath-conduction/BOUT.inp
- examples/1D-sheath-conduction/README.md
- examples/1D-sheath/BOUT.inp
- examples/1D-sheath/README.md
- hermes-3.cxx
- include/evolve_density.hxx
- include/evolve_pressure.hxx
- include/noflow_boundary.hxx
- include/sheath_boundary.hxx
- src/evolve_density.cxx
- src/evolve_momentum.cxx
- src/evolve_pressure.cxx
- src/makefile
- src/noflow_boundary.cxx
- tests/unit/test_noflow_boundary.cxx
Adding no-flow boundary condition so that simulations like SD1D can be run, with an upstream source and downstream sheath boundary.
> Noflow boundary, 1D examples

- include/evolve_pressure.hxx
- src/evolve_pressure.cxx
- src/sheath_boundary.cxx
- Changes to sheath boundary to make it more robust to low densities and temperatures, and limit gradients
- Change pressure equation formulation, to use v * Grad(p) rather than p * Div(v). This seems to help reduce spurious heating of charged ions near the sheath.
> Changes to pressure evolution and sheath boundary

- include/evolve_density.hxx
- include/evolve_pressure.hxx
- src/adas_reaction.cxx
- src/collisions.cxx
- src/evolve_density.cxx
- src/evolve_pressure.cxx
- src/sheath_boundary.cxx
Density and pressure equations can evolve logN and logP, exponentiating each iteration to get the density and pressure.
This may allow more accurate calculation of low-density regions, and prevent negative values in a better way than imposing floors.
> Add evolve_log option

- include/component.hxx
Changes the generic factory (BOUT++ PR https://github.com/boutproject/BOUT-dev/pull/2481), so ComponentFactory definition needs to be modified.
> Update to latest BOUT++ version

- src/amjuel_helium.cxx
- src/anomalous_diffusion.cxx
- Update BOUT++ version to get newer `beuler` solver
- Fix bug in Helium recombination rates
- Change anomalous diffusion method to upwind for all channels
> BOUT++ updates and bug fix

- src/vorticity.cxx
Was already done in phi_boundary_relax=true branch. Without initialising these points, can cause random crashes if any of the uninitialised values happens to be a NaN.
> Initialise second boundary cells of phi when phi_boundary_relax=false

- include/neutral_parallel_diffusion.hxx
- src/neutral_parallel_diffusion.cxx
1. Make pressure an optional input, calculate from density and
temperature if not available. Using IS_SET so that an error
will be thrown if pressure is set afterwards.
2. Add backtrace and use GET_VALUE to record information for
debugging.
> Improve debugging in neutral_parallel_diffusion

- docs/sphinx/examples.rst
- examples/2D-drift-plane-turbulence-te-ti/BOUT.inp
- include/sheath_closure.hxx
- src/sheath_closure.cxx
Allows source-driven 2d turbulence simulations.
If `sheath_closure:sinks = true` is set:
* Sheath particle flux is at a common sound speed of sqrt(P_total/(total mass density)), for all species. Electron particle sink is still modified by DivJsh.
* Ions have an energy sink like `gamma_i*Ti*sheath_flux`, where `gamma_i = 2.0` (by default) is taken from Stangeby's book.
NB These forms have not been chosen carefully - they were just the first that came to my mind!
> Option for density and energy sinks for all species with sheath closure

- src/sheath_boundary.cxx
- src/sheath_boundary_insulating.cxx
- src/sheath_boundary_simple.cxx
- `sheath_boundary_simple` was ok for 1D simulations without electric fields, but needed fixes to work correctly in 3D (to/fromFieldAligned) and with electric fields & currents (setting electron momentum)
- Sheath energy losses should be added to other terms if already set, rather than replacing. 
Should probably make `set` throw an exception if the value has already been set, and add an `overwrite` function.
> Sheath fixes

- src/vorticity.cxx
- tests/integrated/vorticity/data/BOUT.inp
Previously these terms would be silently disabled if sound_speed was not available. Now if `phi_dissipation` or `vort_dissipation` is enabled and `sound_speed` is not available then an error should occur.
> Vorticity get sound_speed if dissipation enabled

- src/hydrogen_charge_exchange.cxx
In SD1D (and potentially Hermes-2) the atomic mass AA is hard-coded in the velocity normalisation Omega_ci. This makes it difficult if we want the code to support different species (or isotopes of a species). This means in Hermes-3 AA is taken out of Omega_ci and must be accounted for explicitly. 
This was done correctly for the amjuel_reaction.hxx modules which cover ionisation, recombination and excitation:
https://github.com/bendudson/hermes-3/blob/e5d86cdc9dde3559ea38a5d63dbbb8b03f2acdd0/include/amjuel_reaction.hxx#L104
However the AA factor was missing in the momentum exchange term for the charge exchange. This pull request fixes this.
> Ensure CX momentum has AA factor

- src/sheath_boundary.cxx
- src/sheath_boundary_insulating.cxx
- src/sheath_boundary_simple.cxx
If the sheath boundary was set *after* other sources of energy, such as atomic reactions, then the previous code would accidentally double those sources/sinks.
This happened because the sheath boundary conditions would:
1. Get the energy_source
2. Add the sheath contribution to energy_source
3. Add the resulting field to the energy_source in the state
This commit fixes this by replacing step 3 with
3*. Set energy_source in the state to the resulting field
> Fix energy source/sink setting in sheath  boundary conditions

- docs/sphinx/components.rst
- include/hydrogen_charge_exchange.hxx
- src/hydrogen_charge_exchange.cxx
Need to be a bit careful with naming of sources/sinks when there are multiple isotopes.
For two species `a` and `b`, the channel `Fab_cx` is a source of momentum for species `a` due to charge exchange with species `b`. There are corresponding sinks for the products of the charge exchange reaction which are not saved. 
For example: 
Reaction `d + t+ -> d+ + t` will save the following forces (momentum sources):
- `Fdt+_cx` is a source of momentum for deuterium atoms `d` and sink of momentum for deuterium ions `d+`.
- `Ft+d_cx` is a source of momentum for tritium ions `t+` and sink of momentum for tritium atoms `t`
The reason for this convention is the existence of the inverse reactions:
`t + d+ -> t+ + d` outputs diagnostics `Ftd+_cx` and `Fd+t_cx`.
> Adding hydrogen CX diagnostics

- examples/blob2d-te-ti/BOUT.inp
- examples/blob2d-te/BOUT.inp
- examples/blob2d/BOUT.inp
The vorticity component has `phi_dissipation` enabled by default, that requires `sound_speed` to be set. Turning off `phi_dissipation`.
> Fix blob2d* examples

- include/amjuel_helium.hxx
- include/amjuel_hyd_ionisation.hxx
- include/amjuel_hyd_recombination.hxx
- include/amjuel_reaction.hxx
- src/amjuel_helium.cxx
- src/amjuel_hyd_ionisation.cxx
- src/amjuel_hyd_recombination.cxx
- src/evolve_density.cxx
- src/evolve_pressure.cxx
Add new diagnose variables S, E, F and R covering particle source, energy transfer, momentum transfer and radiation loss for hydrogenic ionisation and recombination. This does not cover the He reactions but can be easily extended to do so (I think).
Variable names are in the pattern "Sd+_iz", "Fd+_rec" and so on. There is one variable which is an odd one out - "Rd+_ex". The "ex" is there to maintain consistency with Hermes-2 and SD1D, where Riz is specifically the 13.6eV ionisation cost and Rex the remaining radiative losses. Welcome comments on whether this is good or whether it adds more confusion...
The modifications compile and the variables are saved and look plausible at first glance. I will test each of them to make sure it makes sense before upgrading this to a pull request.
> Atomic diagnostics

- include/anomalous_diffusion.hxx
- include/evolve_density.hxx
- include/evolve_pressure.hxx
- src/anomalous_diffusion.cxx
- src/evolve_density.cxx
- src/evolve_pressure.cxx
Reads sources and diffusion coefficients from the mesh, allowing them to be overridden by previous options:
`evolve_density` component
- `N<name>_src` mesh input (e.g. `Ne_src`). Overridden by `source` in `[N<name>]` section. Both have units of particles per cubic meter per second.
`evolve_pressure` component
- `P<name>_src` mesh input (e.g. `Pe_src`). Overridden by `source` in `[P<name>]` section. Both have units of Pascals per second.
`anomalous_diffusion` coefficient
- `D_<name>` mesh input (e.g. `D_e`). Overridden by `anomalous_D`. Both have units of m^2/s. Particle diffusion coefficient.
- `chi_<name>` mesh input (e.g. `chi_e`). Overridden by `anomalous_chi`. Both have units of m^2/s. Heat diffusion coefficient.
- `nu_<name>` mesh input (e.g. `nu_e`). Overridden by `anomalous_nu`. …
> Coefficients and sources in mesh file

- include/amjuel_hyd_ionisation.hxx
- include/amjuel_hyd_recombination.hxx
- include/fixed_density.hxx
- include/fixed_temperature.hxx
- include/fixed_velocity.hxx
- include/hydrogen_charge_exchange.hxx
- include/set_temperature.hxx
- include/upstream_density_feedback.hxx
Use get<>() rather than .as<>() when getting normalisation constants, so value isn't printed to log every time the output is written.
> Tidy outputVars, reduce printing to logs

- include/sheath_boundary.hxx
- include/sheath_boundary_simple.hxx
- include/vorticity.hxx
- src/sheath_boundary.cxx
- src/sheath_boundary_simple.cxx
- src/vorticity.cxx
- tests/unit/test_sheath_boundary.cxx
Can set an input `wall_potential` to bias the `sheath_boundary` and `sheath_boundary_simple` boundary conditions.
> Sheath wall potential

- CMakeLists.txt
- src/collisions.cxx
- tests/integrated/1D-recycling/README.md
- tests/integrated/1D-recycling/data/BOUT.inp
- tests/integrated/1D-recycling/runtest
Introduced in 562f191d1 (July 26th 2022), an `if` rather than `else if` meant that additional collisions were included between ions and electrons if `electron_neutral` was `true` (the default).
This increased the electron collision rate, decreasing electron parallel heat conduction, and increasing the electron temperature.
This adds a new integrated test, `1D-recycling`, that is the same as the example of that name but with fewer cells (50). That is sufficient to check the approximate ion and electron temperatures, and would have caught the bug. The new test should catch changes to electron-ion collisions in future.
> Fix bug in electron collisions

- include/component.hxx
- src/electron_force_balance.cxx
- src/zero_current.cxx
- Apply non-zero floors to density when dividing in `zero_current` and `electron_force_balance`
- Add check in function to set values in the state, to catch non-finite values early
> Low density floors

- include/evolve_momentum.hxx
- src/evolve_momentum.cxx
- src/evolve_pressure.cxx
Changes to improve numerical stability, especially at low density
- Use stronger numerical dissipation in `evolve_momentum` : the fastest wave in the system rather than species sound speed
- Add a term to momentum and pressure equations, that damps the evolving quantity towards consistency with the derived floored quantities e.g. pressure should be consistent with N * T, with T calculated using floored density. In practice this has the effect of damping dynamics in regions where `N < density_floor`.
> Low density improvements

- include/neutral_mixed.hxx
- src/evolve_pressure.cxx
- src/neutral_mixed.cxx
Adds `flux_limit` and `diffusion_limit` options to the `neutral_mixed` component. Finding diffusion coefficients of up to 3000 m^2/s, that cause time integration to be very slow. Applying limits for the first part of a simulation while profiles settle speeds things up considerably.
> Neutral transport flux limits

- include/neutral_mixed.hxx
- src/neutral_mixed.cxx
Extending the custom mesh source changes from https://github.com/bendudson/hermes-3/pull/86 to the neutral_mixed component, allowing custom neutral density and energy sources being specified in the grid and post-processed.
> Add custom neutral sources to neutral_mixed

- include/anomalous_diffusion.hxx
- src/anomalous_diffusion.cxx
It is common to run with a profile of anomalous diffusion coefficients (e.g. with a lower value in the core to represent the transport barrier). It is also useful to change the coefficients while running the model, for example by only imposing a transport barrier after steady state has been achieved with uniform coefficients.
Unfortunately due to input file limitations restricting Y to be continuous around the core, it is not possible to differentiate the PFR from the core in the input file using Heaviside functions. This means that a coefficient profile must be imported from the mesh file (see [PR](https://github.com/bendudson/hermes-3/pull/86)). This poses two problems:
- It is not possible to check that the code is reading the coefficients correctly due to lack of diagnostics
- It is …
> Extra diagnostics and settings for anomalous diffusion

- hermes-3.cxx
- include/scale_timederivs.hxx
- src/evolve_density.cxx
- src/evolve_momentum.cxx
- src/evolve_pressure.cxx
- src/neutral_mixed.cxx
Modify the time derivatives in each cell, scaling to something like the local CFL limit set by electron heat conduction. Intended to help control oscillations in tiny cells near core boundary. May help convergence to steady state for transport problems.
Enable by adding the `scale_timederivs` component once at the top level;
[hermes]
components = e, d+, ..., scale_timederivs
The component will calculate a timestep scaling factor for each cell, based on the electron temperature and the parallel cell size.  That scaling factor is then applied in the `evolve_density`, `evolve_momentum`, `evolve_pressure` and `neutral_mixed` components.
Note that with this the simulation time is not physical meaningful.
> Experimental: Local timestepping for each cell

- CMakeLists.txt
Adds an option `HERMES_UPDATE_GIT_SUBMODULE` which uses identical code to `BOUT_UPDATE_GIT_SUBMODULE`. This is so that you can choose to build `hermes` with a modified local version of BOUT++ in `hermes-3/external/BOUT-dev/`
> Add option to skip submodule update in CMAKE build

- CMakeLists.txt
- docs/sphinx/components.rst
- docs/sphinx/getting_started.rst
- docs/sphinx/index.rst
- hermes-3.cxx
- include/div_ops.hxx
- include/evolve_energy.hxx
- include/hermes_build_config.hxx.in
- src/evolve_density.cxx
- src/evolve_energy.cxx
- src/evolve_momentum.cxx
- src/evolve_pressure.cxx
- src/neutral_mixed.cxx
- tests/integrated/1D-fluid/runtest
- tests/integrated/1D-recycling/runtest
- tests/integrated/sod-shock-energy/README.md
- tests/integrated/sod-shock-energy/data/BOUT.inp
- tests/integrated/sod-shock-energy/runtest
- tests/integrated/sod-shock/runtest
This started as a project to add an `evolve_energy` component, but evolved into a fairly major change to the advection operators. The limiter has become a compile-time choice, and by default changed from MC to MinMod. The results of the Sod shock test are now much improved.
The `evolve_energy` component evolves the sum of internal energy and parallel kinetic energy, as an alternative to the evolve_pressure component. The boundary conditions are not yet imposed correctly, so a note has been added to the manual. I think it's still worth merging this early for all the other improvements.
> Advection operator improvements

- docs/sphinx/index.rst
- docs/sphinx/transport_2d.rst
Working with a branch of BOUT++ to improve the beuler and cvode solvers.
The beuler improvements seem to be helping with 2D transport simulations (compass, 36x48 resolution, 6 cores):
**cvode** 
```
5.000e+03      55185       3.87e+02    80.8    3.2    1.6    0.0   14.5
```
**beuler**
```
5.000e+03      19808       2.83e+02    40.4    0.0    2.6    0.0   56.9
```
That uses the following solver settings:
```
[solver]
type = beuler  # Backward Euler steady-state solver
snes_type = newtonls
ksp_type = gmres
max_nonlinear_iterations = 10
pc_type = hypre
pc_hypre_type = euclid
lag_jacobian = 500
atol = 1e-7
rtol = 1e-5
```
Note that `lag_jacobian` is increased to 500, to reduce the number of times that the preconditioner is rebuilt. Despite that, 56.9% of the runtime is being spent in the …
> Solver improvements

- docs/sphinx/components.rst
- include/ion_viscosity.hxx
- include/vorticity.hxx
- src/ion_viscosity.cxx
- src/vorticity.cxx
Add perpendicular flow parts of the ion viscosity.
If enabled, this damps the ion poloidal flow velocity, with terms in both ion parallel momentum and vorticity equations.
> Ion viscosity

- CMakeLists.txt
- examples/stellarator-2pt-model/BOUT.inp
- hermes-3.cxx
- include/binormal_stpm.hxx
- src/binormal_stpm.cxx
This adds a component which adds binormal transport terms from the stellarator two point model:
http://dx.doi.org/10.1088/0741-3335/53/2/024009
Here we include the field-line pitch effects in the density equation (not just pressure and momentum as in the cited source). There are also additional terms for cross-field drifts in the density  and pressure equations.
There is an example provided.
> Add component for stellarator two-point model 

- README.md
A couple of new users recently didn't realise a specific BOUT++ commit is required when installing Hermes-3. This will need to be updated when we update the BOUT++ version.
> Update the readme to include BOUT++ commit hash

- docs/sphinx/components.rst
- hermes-3.cxx
Original post from Ben:
_Implements Dirichlet boundary condition, labelled "custom" for now. Registered with the BOUT++ boundary factory, so can be used as an option in BOUT.inp_
Mike comments:
- Ben set this up with a dummy clone of a Dirichlet boundary condition for me to work with
- This is the implementation of the radial decay length BC seen in SOLPS/SOLEDGE2D/UEDGE (see BCCON=9 in SOLPS)
- It's often used for plasma density and pressure on the SOL and PFR edges
The new boundary condition can be used in the same way as the other boundary conditions such as `neumann` or `dirichlet`.
For example,
```
[Nd+]
bndry_sol = decaylength(0.003 / hermes:rho_s0)
```
sets up the ion density to decay according to a decay length of 3mm. Note that you need to calculate rho_s0 in the input file to …
> Adding a decay length boundary condition

- docs/sphinx/code_structure.rst
- docs/sphinx/components.rst
- include/div_ops.hxx
- include/evolve_density.hxx
- include/evolve_energy.hxx
- include/evolve_momentum.hxx
- include/evolve_pressure.hxx
- src/anomalous_diffusion.cxx
- src/div_ops.cxx
- src/evolve_density.cxx
- src/evolve_energy.cxx
- src/evolve_momentum.cxx
- src/evolve_pressure.cxx
The `anomalous_diffusion` component now saves flows of particles, momentum and energy through cell faces in the state. The plan is for this to be extended to other components, making cell face flows easier to diagnose.
`PFx = state["species"]["e"]["particle_flow_xlow"]` is the (normalised) number of particles per second passing through the lower X cell face: `PFx(i,j,k)` is the number of particles per second passing from cell `(i-1,j,k)` to `(i,j,k)`. Note that positive flow means flow in the positive coordinate direction. 
Similarly, `PFy = state["species"]["e"]["particle_flow_ylow"]` is the flow of particles through the lower Y cell face.
The rate of change of density in cell `(i,j,k)` due to the flows is:
```
ddt(Ne) = ( PFx(i,j,k) + PFy(i,j,k) - PFx(i+1, j, k) - PFy(i,j+1,k) ) / dV …
```
> WIP: Cell face flow information

- src/hydrogen_charge_exchange.cxx
- src/neutral_mixed.cxx
In `hydrogen_charge_exchange`: Limit Teff to be between 0.01 and 1e4 eV. If Teff becomes too large then sigma_v can become Inf.
In `neutral_mixed`, add checks for finite time-derivatives if `CHECKLEVEL >= 1`.
> Robustness fixes

- docs/sphinx/components.rst
- examples/1D-hydrogen-equalT/BOUT.inp
- examples/1D-hydrogen/BOUT.inp
- examples/1D-hydrogen/qn/BOUT.inp
- examples/1D-neon-source/BOUT.inp
- examples/1D-neon/BOUT.inp
- examples/1D-recycling/BOUT.inp
- examples/1D-recycling/cvode/BOUT.inp
- examples/solkit-comparison/single-temperature/BOUT.inp
- examples/solkit-comparison/two-temperatures/BOUT.inp
- examples/tokamak/recycling-dthe-drifts/BOUT.inp
- examples/tokamak/recycling-dthe/BOUT.inp
- examples/tokamak/recycling-dthene/BOUT.inp
- examples/tokamak/recycling/BOUT.inp
- include/recycling.hxx
- src/recycling.cxx
- tests/integrated/1D-recycling/data/BOUT.inp
First of several BCs required to bring Hermes-3 in line with UEDGE/SOLPS/SOLEDGE2D/etc in terms of boundary conditions.
This requires the PR which enables cell face flows to be saved in the state: https://github.com/bendudson/hermes-3/pull/152
It's required because the perpendicular fluxes are currently calculated in `anomalous_diffusion` and not saved; the operators only output the change in source to the next cell as a result of the flux. At the moment, just the radial and poloidal components of the three anomalous transport channels are saved. These are sufficient to calculate the plasma flux leaving the SOL edge.
Note that for plasma flux to leave the edge you need a free boundary condition on both density (to allow a density gradient and therefore perpendicular diffusion) as well as …
> Add edge recycling

- src/vorticity.cxx
When ion diamagnetic drift is included in the polarisation drift there is an energy exchange between ion energy and perpendicular flow. That term doesn't have a 3/2 factor.
> vorticity: Remove 3/2 from ion diamagnetic energy exchange

- src/collisions.cxx
- tests/unit/test_collisions.cxx
Confusion over normalised vs non-normalised (eV) units, found by @mikekryjak.
Affects ion-neutral and electron-neutral elastic collision rates.
> Fixes for electron-neutral and ion-neutral collisions

- include/collisions.hxx
- src/collisions.cxx
This PR is now scaled back to just the collision frequencies due to a change in priorities. The other objectives will be picked up by a separate PR.
Tasks:
**Original objectives:**
_This PR adds new diagnostic variables for the energy and momentum transfer channels due to all the collisions in `collisions`. This should finally allow us to perform energy and momentum balances on a species basis. The collision frequencies are also saved with the new code `K`, e.g. `Kdd+_coll`. The rates for the various atomic processes are also going to be saved in the same format.
The frictional heating energy sources are saved separately due to the fact that both collision species end up with an energy gain. This prevents us from working out the energy source of species 2 from the inverse of the energy …
> Add collision diagnostics

- docs/sphinx/components.rst
- include/neutral_boundary.hxx
- include/recycling.hxx
- src/neutral_boundary.cxx
- src/recycling.cxx
When hitting a wall, a neutral atom can either undergo thermal reflection (recombine, thermalise with the wall and come off as a molecule) or fast reflection (the atom does not recombine and bounces off, possibly losing some energy in the process). In EIRENE the fate of the particle is determined from the TRIM database.
The only thing we have on this right now is the `neutral_boundary` component which is currently only implemented for the sheath. It uses a sheath heat transmission style expression to allow for neutral energy to be imparted on the wall given a `gamma` parameter. The velocity used for this is the thermal velocity.
This PR adds a diagnostic variable for the heat loss due to this process and extends it to the SOL and PFR edges.
The expression will be following that from D. …
> Allow neutral cooling due to wall reflection

- docs/sphinx/components.rst
- include/recycling.hxx
- src/neutral_boundary.cxx
- src/recycling.cxx
Adds neutral pump for 2D/3D cases. This allows a more physically realistic setup: the target recycling is set to 1 (or almost 1) and the domain particle balance is then controlled by the pump recycle multiplier (i.e. the pump albedo). This means the particle outflow is no longer controlled by the amount of ions flowing into the target along the parallel, but instead by the amount of neutrals flowing to the pump in the perpendicular direction. This kind of condition is common in other codes such as UEDGE, SOLPS and SOLEDGE2D.
The pump location is specified in the grid file in line with what other codes do. You must pass a new Field3D called `is_pump` in the grid file and select pump cells by setting them to `1`. Only cells in the PFR and SOL edge will be picked up - careful not to set it …
> WIP: Add neutral pump

- docs/sphinx/components.rst
- examples/1D-hydrogen-equalT/BOUT.inp
- examples/1D-hydrogen/BOUT.inp
- examples/1D-hydrogen/qn/BOUT.inp
- examples/1D-neon-source/BOUT.inp
- examples/1D-neon/BOUT.inp
- examples/1D-recycling/BOUT.inp
- examples/1D-recycling/cvode/BOUT.inp
- examples/solkit-comparison/single-temperature/BOUT.inp
- examples/solkit-comparison/two-temperatures/BOUT.inp
- examples/tokamak/recycling-dthe-drifts/BOUT.inp
- examples/tokamak/recycling-dthe/BOUT.inp
- examples/tokamak/recycling-dthene/BOUT.inp
- examples/tokamak/recycling/BOUT.inp
- include/recycling.hxx
- src/recycling.cxx
- src/sheath_boundary_simple.cxx
Turns out fast recycling has a big impact. This PR does a simple implementation of this:
$$\Gamma_{E_{n}} = R \times (R_{f} \alpha_{E} \Gamma_{E_{i}}^{sheath}  + (1 - R_{f}) T_{R} \Gamma_{N_{i}})) $$
Where $R$ is the recycle multiplier, $R_{f}$ is the fast reflection fraction, $\alpha_{E}$ is the energy reflection factor,
$\Gamma_{E_{i}}^{sheath}$ is the incident heat flux from the sheath boundary condition, $T_{R}$ is the recycle energy and $\Gamma_{N_{i}}$ is the incident ion particle flux.
This is implemented for the SOL and the PFR and is fully compatible with the neutral pump.
In addition, the example cases haven't been corrected to reflect the new recycling flags - this is now done in this PR for all examples.
Tasks:
> Implement fast recycling

- docs/sphinx/components.rst
- include/amjuel_helium.hxx
- include/amjuel_hyd_ionisation.hxx
- include/amjuel_hyd_recombination.hxx
- include/amjuel_reaction.hxx
- include/fixed_fraction_radiation.hxx
- include/hydrogen_charge_exchange.hxx
- src/amjuel_helium.cxx
- src/amjuel_hyd_ionisation.cxx
- src/amjuel_hyd_recombination.cxx
- src/hydrogen_charge_exchange.cxx
This PR allows the reaction rate for each reaction to be scaled according to a user-set `multiplier`. This will make it easier to determine the impact of a particular reaction. Impurity rates are excluded and left to future work, apart from fixed fraction.
Todo:
> Allow reactions to be arbitrarily scaled up and down

- include/collisions.hxx
- src/collisions.cxx
See title. Adds new setting under `[collisions]`: `ei_multiplier`. This serves as a user-set arbitrary scaling factor on the ei collision rate.
> Add user-set multiplier on e-i collision rate

- include/neutral_mixed.hxx
- src/neutral_mixed.cxx
In 1D neutral momentum is controlled by the `evolve_momentum` which can be easily disabled. In 2D, it is controlled by `neutral_mixed` which has the entire neutral transport model inside it and no option to disable it. This PR adds a new flag called `evolve_momentum` which is `True` by default.
> Allow solving in 2D/3D without neutral momentum equation

- docs/sphinx/components.rst
- src/neutral_boundary.cxx
**Fixing cause of crash**
In testing the multigroup neutral model I found that I couldn't start my 1D baseline test case with both neutral momentum and the neutral boundary enabled. The neutral boundary contains fast/thermal reflection. The symptom was a `-4` crash at `t=0`, which I've also seen before in 2D and elsewhere.
I dug into it a bit and found that the cooling source q was a `nan:`
https://github.com/bendudson/hermes-3/blob/ea5c52d04206424cc18ed8b6d70a1734f7af4064/src/neutral_boundary.cxx#L109
This was because of two instances of division by zero when  `Tn=0` during the first step:
https://github.com/bendudson/hermes-3/blob/ea5c52d04206424cc18ed8b6d70a1734f7af4064/src/neutral_boundary.cxx#L91
https://github.com/bendudson/hermes-3/blob/ea5c52d04206424cc18ed8b6d70a1734f7af4064/src/n …
> Stability improvements and bug fix in neutral wall cooling formulation 

- .gitignore
Every time I build Hermes-3, I do it into a folder in the Hermes-3 source directory and I have `build` in the name. I've been adding `build*` manually to my .gitignore every time I start a new branch for a year now. It has now occurred to me I can just commit this...
> Add build* to .gitignore for Git to ignore build folders

- docs/sphinx/components.rst
- include/fixed_fraction_radiation.hxx
Impurity radiation dominates detachment in reactor-class devices but it's a very nonlinear process partially because of the nonlinearities of the cooling curve:
- Both the LHS and RHS slopes are curved 
- RHS slope tapers off slower than the LHS slope
- RHS slope has a large "shoulder", a region of non-zero radiation at higher temperatures which is also a complex curve
All three features are present in curves of N, Ne, Ar and C to varying degrees. To study the impact of this, I prepared two simplified curves for Argon. `fixed_fraction_argon_simplified1` takes out the curvature from the slopes but preserves their levels:
`fixed_fraction_argon_simplified2` takes out the RHS shoulder:
`fixed_fraction_argon_simplified3` takes out the LHS - RHS asymmetry:
Note that there is an additional point …
> Add simplified Ar cooling curves

- include/classical_diffusion.hxx
- src/classical_diffusion.cxx
Currently working with Chris Ridgers on simple Blob2D example. We need to add some kind of diffusion to it, but we don't want to have to evolve collisions. In this PR I modify the `classical_diffusion` component and add a new setting for a user-set D which bypasses collisions:
https://github.com/bendudson/hermes-3/blob/5d1e3811a7eef4da0d394a37cae97d1de5e1797c/src/classical_diffusion.cxx#L12
This then feeds into particle, momentum and pressure diffusion, but there is an additional bit (possibly conduction?) which has a different formulation. I haven't been able to figure it out yet so I disabled it for now - will need to discuss with @bendudson.
https://github.com/bendudson/hermes-3/blob/5d1e3811a7eef4da0d394a37cae97d1de5e1797c/src/classical_diffusion.cxx#L82-L85
> Allow for classical_diffusion to support user-set diffusion coefficient

- hermes-3.cxx
- src/snb_conduction.cxx
- src/transform.cxx
- tests/unit/test_collisions.cxx
- tests/unit/test_extras.hxx
Updates the default version of BOUT++ that is downloaded by CMake.
Adds some nice features including:
- Support for ADIOS2 file format, for outputs and restarts
- Changes to Options, to make accidental copying much harder
- Update to C++17 standard, with some tidying up
This will be a breaking change, since the `Options::copy()` method was added, replacing the copy constructor.
> Update BOUT++ to latest version

- docs/sphinx/components.rst
- docs/sphinx/tests.rst
- src/electromagnetic.cxx
- src/vorticity.cxx
- tests/integrated/alfven-wave/data/BOUT.inp
Main things:
- Zero-laplace radial boundary condition on Apar by default. Neumann as an option for e.g. slab simulations.
- Note to include Alfven wave in calculation of fastest wave. If omitted, numerical instabilities tend to occur at the target, particularly inboard targets with high B and low density (i.e. high Alfven speed).
> Updates for electromagnetic tokamak simulations

- include/neutral_parallel_diffusion.hxx
- src/neutral_parallel_diffusion.cxx
- tests/integrated/1D-recycling/runtest
Some of the factors in the neutral transport equations have been incorrect. We fixed these in the advanced fluid neutral model implementation in 2D which is still in progress: https://github.com/mikekryjak/hermes-3/blob/E-AFN-neutadv-hotneut/src/neutral_mixed.cxx
There is no reason to not have these implemented in 1D straight away so that the equations are correct. In particular this has been prompted by my comparison against ReMKiT1D with Stefan Mijin.
The fixes are:
- The pressure advection factor is now 5/2 instead of 3/2. This corresponds to the V grad P form without the compression term and is closer to the solution with the compression term than the P div V form. It is also what's used in the AFN model (Horsten 2017)
- The factor on kappa should be 5/2 as per Chapman-Enskog and as …
> Fixing 1D neutral transport equations

- src/evolve_pressure.cxx
Added Tnorm to kappa_par conversion in evolve_pressure (currently line https://github.com/bendudson/hermes-3/blob/8c450228e61d66200de225c168aa80fdfd91f7b2/src/evolve_pressure.cxx#L435)
The kappa_par conversion in evolve pressure was missing a factor of 1/Tnorm, causing the resulting conductivity to be too high. For the 1D recycling case Tnorm = 100 eV, which meant that calculated heat flux would be two orders of magnitude higher than supplied to the system via the pressure source. I've plotted this for the electron parallel conducitve heat flux (see below):
The sharp eyed may see that the electron heat flux is increasing between the x point and the target, above the supplied power, this is mirrored exactly by the ion heat flux, so energy is still conserved.
> Fixing kappa_par conversion

- docs/sphinx/components.rst
- src/collisions.cxx
These may be double-counted if atomic reactions are included. Added a note to the manual.
ion-electron, electron-electron, ion-ion, and neutral-neutral collisions are still enabled by default.
Fixes #241.
> collisions: Disable ion-neutral and electron-neutral by default

- docs/sphinx/code_structure.rst
- docs/sphinx/components.rst
- include/div_ops.hxx
- include/electromagnetic.hxx
- include/vorticity.hxx
- src/div_ops.cxx
- src/electromagnetic.cxx
- src/evolve_density.cxx
- src/evolve_energy.cxx
- src/evolve_momentum.cxx
- src/evolve_pressure.cxx
- src/sheath_boundary.cxx
- src/vorticity.cxx
More work on electromagnetic simulations. Now running in axisymmetric simulations at least. Still testing in 3D.
- Add missing term to momentum equation, needed for energy conservation
- Add option to force phi to be constant on core boundary
- By default set Apar to zero on SOL and PF boundary, zero-gradient on core boundary.
Commit [b1d627f](https://github.com/bendudson/hermes-3/pull/230/commits/b1d627f44d87dce7023f49f55a90a4abb67d7945) fixes issue #237 by setting the boundary conditions on the saved variable.
> Electromagnetic simulations

- src/vorticity.cxx
Otherwise the name of phi is not reset, as assigning a FieldPerp to a Field3D does not reset the name.
> Set name for potential

- CMakeLists.txt
- tests/unit/test_extras.hxx
Using a branch `hermes3-temp` rather than `next`, to keep some patches for additional limiters.
> Upgrade BOUT++ to latest next

- docs/sphinx/components.rst
- include/fixed_fraction_radiation.hxx
Fitted to ADAS data using Radas and M.Kryjak's scripts. n = 1e20 m^-3 and tau = 0.5ms as other rates.
Xenon and Tungsten required 15 and 20 coefficients to get reasonable fits to the data.
> fixed_fraction_radiation: Add Krypton, Xenon, Tungsten

- include/electromagnetic.hxx
- src/electromagnetic.cxx
An iterative method (Naulin solver) is used to solve for Apar. This may not converge unless given a close initial guess. Problems were encountered when restarting in states with large density perturbations.
This saves Apar to the restart file, and loads it if available.
Also updated the iterative Naulin solver, to accept loose tolerances after maxits iterations is reached. This usually happens for a few calls and then reverts to tight tolerances.
> electromagnetic: Load and save Apar to restarts

- .gitignore
- docs/sphinx/components.rst
- include/div_ops.hxx
- include/evolve_pressure.hxx
- include/neutral_mixed.hxx
- include/sheath_boundary_simple.hxx
- src/div_ops.cxx
- src/electron_force_balance.cxx
- src/evolve_density.cxx
- src/evolve_energy.cxx
- src/evolve_momentum.cxx
- src/evolve_pressure.cxx
- src/neutral_mixed.cxx
- src/sheath_boundary_simple.cxx
- src/upstream_density_feedback.cxx
Working on power balance diagnostics in 1D test case. 
MK edit:
This one turned into quite a journey into resolving an energy imbalance which went as high as 20% for an attached case. There are several fixes, as well as improvements that minimise zigzags at the boundary (a phenomenon that all codes struggle with if they don't have staggered grids) and new diagnostics. The diagnostics allowed us to reach a milestone - the first proper total energy flux balance.
Summary of changes:
- https://github.com/bendudson/hermes-3/pull/248/commits/e371fc7e6aac6d4d915c06a3f57897a627ba63f0: Viscous heating due to the diffusion of kinetic energy caused by the Lax flux viscosity
- https://github.com/bendudson/hermes-3/pull/248/commits/50bff348e455b607c2a1fd7df6cf60bdc84232b7 and …
> WIP: Multiple improvements to sheath boundary and energy balance

- src/zero_current.cxx
Accidentally evolving momentum and setting zero current should throw an exception.
> zero_current: throw exception if velocity already set

- src/electromagnetic.cxx
Adding output diagnostics for aparSolver. Changing defaults to allow more iterations, which seem to sometimes be necessary.
> Electromagnetic solver settings

- src/collisions.cxx
- src/evolve_pressure.cxx
S. Mijin Identified a discontinuity in the NRL formulary fits for the electron ion coulomb log, this can be rectified by altering the change over point to exp(2.0) see attached.
> Coulomb log fix

- docs/sphinx/index.rst
- docs/sphinx/installation_using_spack.rst
I have added a page to the docs to show how Spack (https://spack.readthedocs.io/en/latest/basic_usage.html#installing-and-uninstalling) can be used to help the Hermes-3 installation by managing the basic modules needed for Hermes-3. I have tested that the `html` docs build locally. You can see the online docs here https://hermes3--273.org.readthedocs.build/en/273/installation_using_spack.html.
Hopefully complimentary to the existing installation instructions. Happy to modify the notes according to any comments.
> Notes on how to use Spack to install PETSc and Hermes-3

- include/electron_force_balance.hxx
- src/electron_force_balance.cxx
If `electron_force_balance:diagnose=true` then Epar will be saved to the output (dmp) files.
> electron_force_balance: Add Epar output diagnostic

- include/recycling.hxx
- src/recycling.cxx
Each recycling channel now outputs diagnostics for particle/momentum/energy sources.
Previously there was only one diagnostic for all channels.
> recycling: Diagnostics should be per-channel

- docs/requirements.txt
- docs/sphinx/conf.py
This PR changes the docs theme to be like BOUT++, see screenshot below. This theme is `sphinx_book_theme` and you must pip install it before building the docs locally. The theme is the same on Readthedocs as locally which helps to make the docs writing experience more predictable - we previously had a different theme locally and it made things look very different once they were up.
One thing I would appreciate feedback on is how to add `sphinx_book_theme` to some sort of python environment requirements so that users don't get confused. I don't think we give any instructions right now on how to build the documentation, so maybe we could add a documentation page on that and instruct the user to install the right theme there? Happy to do that if you think that's the right way forward.
Would …
> Unify docs theme with BOUT++

- docs/sphinx/components.rst
- include/fixed_fraction_radiation.hxx
In fixed fraction impurity radiation models, it's assumed that the impurity fraction and cooling curve remain constant throughout the domain. In reality, the impurities in the core have a much longer residence time than ones in the edge, which reduces their radiation power to coronal levels. 
Based on conversations with David Moulton, this can be emulated by simply disabling core radiation. This can prevent runaway detachment fronts.
This PR includes the option `no_core_radiation` and sets it to **True** by default.
> fixed-fraction-radiation: Disable core radiation by default

- docs/sphinx/components.rst
- src/evolve_momentum.cxx
- src/evolve_pressure.cxx
- src/vorticity.cxx
Work in progress, adding and (soon) testing electromagnetic flutter terms.
> Magnetic flutter terms

- include/recycling.hxx
- src/recycling.cxx
Solves https://github.com/boutproject/hermes-3/issues/250
Solves https://github.com/boutproject/hermes-3/issues/305
There has been a bug for ages which causes a crash when starting a case with radial recycling from scratch. Turns out it's actually a problem with the pump. I put a free BC in there:
https://github.com/boutproject/hermes-3/blob/a33e1ba046a4090ac588dc53ab1ff0017515c0ff/src/recycling.cxx#L352-L358
This is a problem as neutrals are often initialised with zero density, causing a divide by zero and the error message:
> ====== Exception thrown ======
Setting invalid value for 'species:d:density_source'
I have now floored density, pressure and temperature:
https://github.com/boutproject/hermes-3/blob/d8232ba74430d92cb21fb462d90e300482c1161c/src/recycling.cxx#L175-L177
The floored …
> Add flooring to neutral pump 

- include/sheath_boundary_simple.hxx
- src/sheath_boundary_simple.cxx
This PR is split off from https://github.com/boutproject/hermes-3/pull/195. It has been used in the verification against the 1D code ReMKiT1D. Note that this is for `sheath_boundary_simple` only. It is aimed to merge all the various sheath boundary components into one over the next few months. 
**What's new**
How the sheath boundary works in `sheath_boundary_simple` is now easier to understand by having expanded the calculations by a few steps, e.g. instead of this, which obscures the target cross-sectional area and cell volume:
```
// Multiply by cell area to get power
BoutReal heatflow = q * (coord->J[i] + coord->J[ip])
/ (sqrt(coord->g_22[i]) + sqrt(coord->g_22[ip]));  // This omits dx*dz because we divide by dx*dz next
// Divide by volume of cell to get energy loss rate (> 0)
BoutReal …
```
> sheath_boundary_simple: minor refactor, add diagnostics

- docs/sphinx/developer.rst
- examples/tokamak-1D/1D-threshold/BOUT.inp
- hermes-3.cxx
- hermes-3.hxx
- include/evolve_pressure.hxx
- include/hermes_utils.hxx
- include/neutral_mixed.hxx
- src/adas_reaction.cxx
- src/collisions.cxx
- src/evolve_density.cxx
- src/evolve_energy.cxx
- src/evolve_momentum.cxx
- src/evolve_pressure.cxx
- src/neutral_mixed.cxx
- src/sheath_boundary.cxx
- src/sheath_boundary_insulating.cxx
- src/sheath_boundary_simple.cxx
- src/sound_speed.cxx
- src/vorticity.cxx
- Replace "hard" `floor()` function with a differentiable function `softFloor()` when applying non-zero limits. The intention is to avoid non-differentiable switches in the RHS function, making convergence of the solver easier.
- Remove `ddt(P) += N*T - P` term by default in `evolve_pressure`. This term tries to drive `P` toward being consistent with `N * T`, becoming active when `N < density_floor`. This term is the cause of the low neutral temperatures seen in 1D simulations in low density regions. See #303 
- Add a `linear` flag to the state, that is `true` when the time integrator is performing a linear solve. This may be used in components to linearise the RHS and maybe improve performance. See #276 
- Modify `neutral_mixed` so that it consistent with `evolve_density`, …
> Smooth floors, improve low density regions

- src/evolve_pressure.cxx
If velocity is not set then `flow_ylow` was not initialized. This is a diagnostic output that is only needed if `diagnose=true`.
> evolve_pressure: Initialize flow_ylow if diagnose but no velocity

- src/neutral_mixed.cxx
> Several fixes for neutral_mixed

- include/adas_reaction.hxx
- include/hydrogen_charge_exchange.hxx
- include/reaction.hxx
- include/solkit_hydrogen_charge_exchange.hxx
- src/reaction.cxx
Adds a temporary struct from which all reaction component classes inherit.
Interim solution until the reactions refactoring is finished!
Fixes #395
> Fix reaction string extraction
